### ISSUE TITLE
DSNT support only 1 point in 1 heatmap？

### ISSUE THREAD

**Issue by skylook** [anibali/dsntnn#16]
DSNT support only 1 point in 1 heatmap？
How to get poses of multi people in one image?

**Comment by anibali** [comment]
Right, it only supports one point per heatmap, so it won't work for multiple people out-of-the-box. I've seen others get around this issue by using a multi-stage approach, where the first stage detects multiple instances of people, and the second stage uses DSNT on a sub-region of the image cropped around the detection. But you might find that another approach is more suitable for your application, since DSNT was really designed with a fixed number of points in mind.

**Comment by hichem-abdellali** [comment]
Hi @skylook ,

May I ask you if you managed to find out a way to return many points in a single heatmap ?

Thanks
