### ISSUE TITLE
Is Frobenius computed correctly?

### ISSUE THREAD

**Issue by saix47** [anibali/dsntnn#2]
I look up your code at _coord_expectation function. I'm not fully understand why you sum heatmaps (Z) _before_ inner product with own_coords (X or Y) (then you do sum it again). I thought it must be summed _after_ inner product of heatmaps and own_coords? This really makes me confuse because in your paper, you describe in Figure 3 differently.

**Comment by anibali** [comment]
What you're seeing is an optimisation. Each row (column) of X (Y) is the same. So rather than represent own_coords (X/Y) as a matrix, I represent it as a vector. Then, to actually calculate the expectation, I calculate the marginal probabilities (first sum), then do the inner product (second sum). The result is exactly the same.

Here's the maths (remember, each row of X is the same):

![](http://mathurl.com/y738287w.png)

**Comment by saix47** [comment]
Thank you for your explanation. I understand it. The problem was when I try to test the _coord_expectation I chose dim as positive number, but to apply your code, it should be negative (otherwise must change the for loop inside it).
Now everything's clear.
